### ISSUE TITLE
Cannot change column used in foreign key constraint

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#461]
SQLSTATE[HY000] [1832] Cannot change column 'track_id': used in a foreign key constraint 'c_fk_views_track_id'

**STACK TRACE:**

#0 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(413): RedBeanPHP\Driver\RPDO->runQuery()
#1 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(72): RedBeanPHP\Driver\RPDO->Execute()
#2 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(1073): RedBeanPHP\Adapter\DBAdapter->exec()
#3 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(116): RedBeanPHP\QueryWriter\AQueryWriter->widenColumn()
#4 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(206): RedBeanPHP\Repository\Fluid->modifySchema()
#5 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php(432): RedBeanPHP\Repository\Fluid->storeBean()
#6 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(357): RedBeanPHP\Repository->store()
#7 /usr/share/nginx2/libs/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(458): RedBeanPHP\OODB->store()
#8 /usr/share/nginx2/libs/StarterKit/DB.php(49): RedBeanPHP\Facade::store()
#9 /usr/share/nginx2/libs/StarterKit/DB.php(512): StarterKit\DB->store()
#10 /usr/share/nginx2/libs/StarterKit/Routes/API.php(574): StarterKit\DB->viewIncr()

```php

	public function viewIncr($type,$id,$uniq)
	{
		switch($type){
			case 'mixtape':
				$exist = \R::getRow('SELECT * FROM views WHERE timestamp >:t AND mixtape_id=:id AND uniq=:u',
					[':t'=>time() - (60 * 60 * 2),':id'=>$id,':u'=>$uniq]
				);
				if(empty($exist)){
					$t = $this->model('views');
					$t->mixtape_id = $id;
					$t->uniq = $uniq;
					$t->timestamp = time();
					$this->store($t);
				}
			break;
			case 'single':
				$exist = \R::getRow('SELECT * FROM views WHERE timestamp >:t AND track_id=:id AND uniq=:u',
					[':t'=>time() - (60 * 60 * 2),':id'=>$id,':u'=>$uniq]
				);
				if(empty($exist)){
					$t = $this->model('views');
					$t->track_id = $id;
					$t->uniq = $uniq;
					$t->timestamp = time();
					$this->store($t);
				}
			break;
			default:
				throw new \exception('bad request');
			break;
		}
	}
```

table views can except either a `track.id` or `mixtape.id` as foreign key constraint. works on several other tables, but on this particular one inserting a record for a `mixtape` triggers the error. inserting a record for a `track` does not trigger the error. `model()` and `store()` are wrappers around redbean functions to eliminate tedious tasks and validations.

**Comment by r3wt** [comment]
My mistake. i had made a mistake in my controller and was attempting to use a mixtape_id for a track_id, where the mixtape_id was not a key present in tracks.
