### ISSUE TITLE
Enum tables not created

### ISSUE THREAD

**Issue by mrdamien** [gabordemooij/redbean#464]
Redbeanphp: 4.2.5
pdo_sqlite: 3.7.9
php: 5.6.12 

I remember this working in the past, and the documentation seems to say it should work: 

"*The ENUM method will do a lot of work here. First it checks whether there exists a 'flavour' bean with the name 'ENGLISH'. If this is the case, enum() will return this bean, otherwise it will create such a bean, store it in the database and return it. This way your ENUMs are created on the fly - properly.*"

```php
<?php
include '../rb.php';
$file = __DIR__.DIRECTORY_SEPARATOR.'test.sqlite';
unlink($file);
R::setup('sqlite:'.$file);
R::DEBUG(TRUE);

$test = R::dispense('test');

$test->name = "this is a test";
R::store($test);

$test->type = R::enum('colour:foobar');
R::store($test);
```

### Output

```
SELECT name FROM sqlite_master
			WHERE type='table' AND name!='sqlite_sequence';<br>
Array
(
)
<br>
resultset: 0 rows<br>
CREATE TABLE `test` ( id INTEGER PRIMARY KEY AUTOINCREMENT ) <br>
Array
(
)
<br>
PRAGMA table_info('test')<br>
Array
(
)
<br>
resultset: 1 rows<br>
ALTER TABLE `test` ADD `name` TEXT <br>
Array
(
)
<br>
INSERT INTO `test` ( id, `name` ) VALUES
			( NULL, ? ) <br>
Array
(
    [0] => this is a test
)
<br>
SELECT `colour`.*  FROM `colour`  -- keep-cache<br>
Array
(
)
<br>
An error occurred: SQLSTATE[HY000]: General error: 1 no such table: colour<br>

Fatal error: Uncaught [0] - SQLSTATE[HY000]: General error: 1 no such table: colour
trace: #0 /home/mrdamien/PhpstormProjects/rb.php(853): RedBeanPHP\Driver\RPDO->runQuery('SELECT `colour`...', Array)
#1 /home/mrdamien/PhpstormProjects/rb.php(3305): RedBeanPHP\Driver\RPDO->GetAll('SELECT `colour`...', Array)
#2 /home/mrdamien/PhpstormProjects/rb.php(5003): RedBeanPHP\Adapter\DBAdapter->get('SELECT `colour`...', Array)
#3 /home/mrdamien/PhpstormProjects/rb.php(6984): RedBeanPHP\QueryWriter\AQueryWriter->queryRecord('colour', Array, NULL, Array)
#4 /home/mrdamien/PhpstormProjects/rb.php(8046): RedBeanPHP\Repository->find('colour', Array, NULL, Array)
#5 /home/mrdamien/PhpstormProjects/rb.php(9850): RedBeanPHP\OODB->find('colour')
#6 /home/mrdamien/PhpstormProjects/rb.php(11280): RedBeanPHP\LabelMaker->enum('colour:foobar')
#7 /home/mrdamien/PhpstormProjects/mrd-blog/test.php(20): RedBeanPHP\Facade::enum('colour:foobar')
#8 {main}
  thrown in /home/mrdamien/PhpstormProjects/rb.php on line 691
```

**Comment by gabordemooij** [comment]
Looks like for some reason this runs in frozen mode.
Can you try to explicitly enable fluid mode by putting R::freeze(false) right before the last R::store?
Over here it works as expected, I see the error but it gets ignored properly (this kind of error, i.e. no such column/table is allowed in fluid mode).

**Comment by mrdamien** [comment]
No change with R::freeze(false);.

**Comment by mrdamien** [comment]
So. I don't know the way it **should** be done, but seems like this is a fix:

```
--- a/RedBeanPHP/LabelMaker.php
+++ b/RedBeanPHP/LabelMaker.php
@@ -147,6 +147,10 @@ class LabelMaker
                        $value                = preg_replace( '/\W+/', '_', strtoupper( trim( $value ) ) );
                }
 
+
+               
+               if (!$this->toolbox->getWriter()->tableExists($type)) goto create;
+
                $values = $oodb->find( $type );
 
                if ( $value === FALSE ) {
@@ -157,6 +161,8 @@ class LabelMaker
                                if ( $enumItem->name === $value ) return $enumItem;
                }
 
+               create:
+
                $newEnumItems = $this->dispenseLabels( $type, array( $value ) );
                $newEnumItem  = reset( $newEnumItems );
```

**Comment by mrdamien** [comment]
Update: it seems xdebug is interfering with the exception handling somehow. Disabling xdebug works.

**Comment by mrdamien** [comment]
Last update for google-ers:

I think (but not confident) that this is a bug with xdebug. Since the exception is caught within redbeanphp xdebug should not be showing errors - yet it did.

So set "xdebug.default_enable = 0" (default is 1) to prevent that.

Am using xdebug v2.3.2
