### ISSUE TITLE
redbean places too many constraints on foreign keys, resulting in unremovable records

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#465]
tables:

artist
mixtape
track

when creating a mixtape or track, script looks up to see if artist exists, if not it creates it and adds the inserted id as `artist_id` to mixtape/track model. this all works great, however redbean places overlapping constraints here, where no constraint is needed. either table should be able to reference an artist with `artist_id` but each table instead places its own constraint on the table.

**Comment by gabordemooij** [comment]
Example? Code snippet?

**Comment by r3wt** [comment]
```php

R::begin();
try
{
	$mixtape = R::model('mixtape');

	...

	$artist = $filter->rmnl($filter->min($post['artist']));
	
	if($db->exists('artist','name',$artist)){
		$mixtape->artist_id = $db->idBy('artist','name',$artist);
	}else{
		$t2 = R::dispense('artist');
		$t2->name = $artist;
		$mixtape->artist_id = R::store($t2);
	}
	
	...
	
	$mixtape_id = R::store($mixtape);
	
	R::commit();
}
catch(exception $e)
{
	R::rollback();
}
```

I am unable to delete artists or tracks or mixtapes as a result of the constraints placed by redbean.

**Comment by gabordemooij** [comment]
I dont see conflicting keys (does that exist?) - I just see you're trying to remove a row that's part of a FK reference - which is not unusual. Either disable FKs before deleting rows and breaking constraints or remove the rows in the right order (my guess is ).
Can you send me a 'show create table' of mixtape, artist and track?

**Comment by gabordemooij** [comment]
Sorry, mistake! My statement applies to dropping tables. If you drop tables you have to follow the order of the FKs.

**Comment by gabordemooij** [comment]
Makes me wonder... are you deleting records, or tables? I have never seen the error message above when deleting a record, only when I try to drop a table or a database.

**Comment by r3wt** [comment]
this problem has reared its head and caused a serious issue in our application. the following is the api route affected, and the associated database function, which relies on redbean to do the heavy lifting.

```php

//api route function
public function view()
public function view()
{
	$app = $this->app;
	$db  = $app->db;
	$get = $app->get;
	
	if(!isset($get['type']) || !isset($get['id'])){
		throw new \exception('');
	}
	
	$type = $get['type'];
	$id   = $get['id'];
	$uniq = <REDACTED>;
	$db->viewIncr($type,$id,$uniq);
	return ['error'=>0,'message'=>1];
}



//db function in question
public function viewIncr($type,$id,$uniq)
{
	switch($type){
		case 'mixtape':
			$exist = \R::getRow('SELECT * FROM views WHERE timestamp >:t AND mixtape_id != NULL AND mixtape_id=:id AND uniq=:u',
				[':t'=>time() - (60 * 60 * 2),':id'=>$id,':u'=>$uniq]
			);
			if(empty($exist)){
				$t = $this->model('views');
				$t->mixtape_id = $id;
				$t->uniq = $uniq;
				$t->timestamp = time();
				$this->store($t);
			}
		break;
		case 'single':
			$exist = \R::getRow('SELECT * FROM views WHERE timestamp >:t AND track_id != NULL AND track_id=:id AND uniq=:u',
				[':t'=>time() - (60 * 60 * 2),':id'=>$id,':u'=>$uniq]
			);
			if(empty($exist)){
				$t = $this->model('views');
				$t->track_id = $id;
				$t->uniq = $uniq;
				$t->timestamp = time();
				$this->store($t);
			}
		break;
		default:
			throw new \exception('bad request');
		break;
	}
}
```

The table `views`:

	1	idPrimary	int(11)
	2	mixtape_id	int(11)
	3	uniq	varchar(191)	
	4	timestamp	int(11)	
	5	track_id	int(11)	
	

You can see that this table relies on two foreign keys, `mixtape_id` OR `track_id`. a record can contain either one, but not both. 

in this version of our database, the first thing added was a `mixtape`. the first thing viewed was a `mixtape`. there is no problem adding a view to a mixtape, but because of the constraints placed by redbean, inserting views for tracks is not possible. the following is the exception that occurs:

```php

{

    "error":1,
    "message":"SQLSTATE[HY000] [1832] Cannot change column 'mixtape_id': used in a foreign key constraint 'c_fk_views_mixtape_id'
    /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php @ Line 176
    STACK TRACE:
    #0 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(413): RedBeanPHP\Driver\RPDO->runQuery() #1 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(72): RedBeanPHP\Driver\RPDO->Execute() #2 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(1073): RedBeanPHP\Adapter\DBAdapter->exec() #3 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(116): RedBeanPHP\QueryWriter\AQueryWriter->widenColumn() #4 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(206): RedBeanPHP\Repository\Fluid->modifySchema() #5 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php(432): RedBeanPHP\Repository\Fluid->storeBean() #6 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(357): RedBeanPHP\Repository->store() #7 /usr/share/nginx/libs/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(458): RedBeanPHP\OODB->store() #8 /usr/share/nginx/libs/StarterKit/DB.php(60): RedBeanPHP\Facade::store() #9 /usr/share/nginx/libs/StarterKit/DB.php(887): StarterKit\DB->store() #10 /usr/share/nginx/libs/StarterKit/Routes/API.php(586): StarterKit\DB->viewIncr() #11 (): StarterKit\Routes\API->view() #12 /usr/share/nginx/libs/StarterKit/Routes/API.php(62): call_user_func() #13 /usr/share/nginx/libs/routes.php(71): StarterKit\Routes\API->__try() #14 (): Closure$#9() #15 /usr/share/nginx/libs/vendor/slim/slim/Slim/Route.php(468): call_user_func_array() #16 /usr/share/nginx/libs/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch() #17 /usr/share/nginx/libs/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #18 /usr/share/nginx/libs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #19 /usr/share/nginx/libs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call() #20 /usr/share/nginx/libs/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call() #21 (): Slim\Slim->run() #22 /usr/share/nginx/libs/StarterKit/App.php(176): call_user_func() #23 /usr/share/nginx/html/index.php(39): StarterKit\App->__call() #24 {main}"

}
```

I care about the library so i want this fixed, but in the meantime can you instruct me how to remove the key constraints? this is beyond my experience level with SQL.

**Comment by mrdamien** [comment]
Try casting $id to int - sounds like redbean is trying to change it to string?

```
$t->track_id = (int)$id;
```

**Comment by r3wt** [comment]
@mrdamien that isn't the issue. the issue that one of the fields that has constraint is `null`. for example, if adding a `view` for a `mixtape`, `track_id` will be `null`, and conversely when adding a `view` for a `track`, `mixtape_id` will be null.
