### ISSUE TITLE
A database has already been specified for this key

### ISSUE THREAD

**Issue by Terkhos** [gabordemooij/redbean#506]
I'm having some problem with the connection and usage, it already happened twice and i  ain't using addDatabase, i only use setup.

To make it work again i have to set R::$toolboxes = []; on the addDatabase method inside de Facade.php

My structure is:

API
    UserAPI
           User
                DAL (this is where i use it)

This is the DAL class

`namespace Models;

use Config\Helpers as Helpers;
use Lib\RedBean\R as R;
use Lib\RedBean\Plugin\ModelValidation as ModelValidation;

class DAL extends R
{
	function __construct()
	{
		R::setup( "mysql:host=localhost;dbname=angularjs", "angularjs", "root" );
		R::ext("validate", function($bean)
		{
		    return ModelValidation::validate($bean);
		});
	}
}`

Exception:

`Fatal error:  Uncaught exception 'Lib\RedBean\RedException' with message 'A database has already been specified for this key.' in D:\Projetos\Market Media\backend\Lib\RedBean\Facade.php:288
Stack trace:
#0 D:\Projetos\Market Media\backend\Lib\RedBean\Facade.php(206): Lib\RedBean\Facade::addDatabase('default', 'mysql:host=loca...', 'angularjs', 'root', false)
#1 D:\Projetos\Market Media\backend\Models\DAL.php(13): Lib\RedBean\Facade::setup('mysql:host=loca...', 'angularjs', 'root')
#2 D:\Projetos\Market Media\backend\Models\Usuario.php(67): Models\DAL-&gt;__construct()
#3 D:\Projetos\Market Media\backend\Models\Usuario.php(56): Models\Usuario-&gt;criaToken('27')
#4 D:\Projetos\Market Media\backend\API\UsuarioAPI.php(42): Models\Usuario-&gt;criaUsuario()
#5 D:\Projetos\Market Media\backend\API\BaseAPI.php(82): API\UsuarioAPI-&gt;criaUsuario(Array)
#6 D:\Projetos\Market Media\backend\Controllers\UsuarioController.php(13): API\BaseAPI-&gt;processAPI()
#7 D:\Projetos\Market Media\backend\index.php(26): Controllers\UsuarioController->start()
in D:\Projetos\backend\Lib\RedBean\Facade.php on line 288`

**Comment by Terkhos** [comment]
Yeah, the team managed to find the problem, it was on the instantiation of the method
